language: generic
sudo: required
services: 
  - docker
before_install:
  - docker build -t amrutrayabagi/react-test -f ./client_new/Dockerfile.dev ./client_new

script:
  - docker run -e CI=true amrutrayabagi/react-test npm test -- --coverage

after_success:
  - docker build -t amrutrayabagi/multi-client ./client_new
  - docker build -t amrutrayabagi/multi-nginx ./nginx
  - docker build -t amrutrayabagi/multi-server ./server
  - docker build -t amrutrayabagi/multi-worker ./worker

  # take those images and push to docker hub
  # login 
  - docker login $DOCKER_ID $DOCKER_PASSWORD
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push amrutrayabagi/multi-client
  - docker push amrutrayabagi/multi-nginx
  - docker push amrutrayabagi/multi-server
  - docker push amrutrayabagi/multi-worker
